### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by fate8383** [kopiro/homebridge-playstation#23]
Latest version causing warnings as below. added to node settings "--trace-warnings" to get the output as below.

(node:3218) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:595:17)
    at Socket.addListener (node:events:617:10)
    at UdpDiscoveryNetworkFactory.createRawMessages (/usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/discovery/udp.js:132:16)
    at UdpDiscoveryNetworkFactory.createMessages (/usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/discovery/udp.js:113:21)
    at UdpDiscoveryNetworkFactory.createDevices (/usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/discovery/udp.js:148:21)
    at /usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/discovery/standard.js:16:99
    at Array.map (<anonymous>)
    at Object.createDevices (/usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/discovery/standard.js:16:76)
    at Discovery.discover (/usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/discovery.js:22:45)
    at PendingDevice.<anonymous> (/usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/device/pending.js:61:55)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/device/pending.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/device/pending.js:4:12)
    at PendingDevice.resolve (/usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/device/pending.js:55:16)
    at PendingDevice.<anonymous> (/usr/lib/node_modules/homebridge-playstation/node_modules/playactor/dist/device/pending.js:37:41)

**Comment by ZhibinLiIntel** [comment]
I have the same issue.

**Comment by kopiro** [comment]
This is not an error, it's just a warning.
