### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toUpperCase')

### ISSUE THREAD

**Issue by Aransh** [kopiro/homebridge-playstation#86]
**Describe The Bug:**
Since version v1.5.2, the plugin crashes on startup with error "Cannot read properties of undefined (reading 'toUpperCase')"

**To Reproduce:**
Update from v1.5.1 to v1.5.2

Worth mentioning - originally I updated, changed the console name, and then restarted homebridge.
Once I saw it was crashing, I removed the name and restarted again, but I'm seeing it still crashes...

**Expected behavior:**
Plugin connects to Playstation successfully

**Logs:**

```
[11/15/2023, 12:19:17 PM] TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at /var/lib/homebridge/node_modules/homebridge/src/server.ts:445:75
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/var/lib/homebridge/node_modules/homebridge/src/server.ts:401:27)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:176:29)
[11/15/2023, 12:19:17 PM] Got SIGTERM, shutting down Homebridge...
[11/15/2023, 12:19:17 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:513:28)
    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
```

**Plugin Config:**

```json
        {
            "apps": [],
            "_bridge": {},
            "pollInterval": 5000,
            "platform": "playstation"
        }
```

**Environment:**

* **Plugin Version**: v1.5.2
* **Homebridge Version**: 1.7.0
* **Node.js Version**: v18.16.0
* **NPM Version**: 9.5.1
* **Operating System**: Arambian 23.05.1

**Comment by kopiro** [comment]
Fixing it now, thanks!

**Comment by kopiro** [comment]
Hey @Aransh , do you think you can help me testing this PR? https://github.com/kopiro/homebridge-playstation/pull/88

**Comment by Aransh** [comment]
Sure, how would I go about installing this on my homebridge?

**Comment by kopiro** [comment]
Hello, this issue has been solved in https://github.com/kopiro/homebridge-playstation/releases/tag/v1.6.0
